POST http://localhost:3200/api/user/register
content-type: application/json

{
    "userName": "Admin",
    "name": "emanuel Abreu",
    "password": "   Emanuel15",
    "rePassword": "Emanuel15  ",
    "type": "tec",
    "position": "analista",
    "document": "27571773",
    "department": "tecnolgia"
}

###
POST http://localhost:3200/api/user/login
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ4YjQ4ZDk5MGZkYzM2MmYyNTk2OGMiLCJ1c2VyTmFtZSI6ImVtYW51ZWwgQWJyZXUiLCJkb2N1bWVudCI6IjI3NTcxNzczIiwicm9sIjoidXNlciIsInBvc2l0aW9uIjoiYW5hbGlzdGEiLCJkZXBhcnRtZW50IjoidGVjbm9sZ2lhIiwiaWF0IjoxNjU4NDU0MzMwLCJleHAiOjE2NTg1NDA3MzB9.UcCtX4ZvglrAkYOM9DchW6vGTArqYab_ZYKPOL2t4vM

{
    "userName": "Admin",
    "password": "   Emanuel15"
}

###
GET http://localhost:3200/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ4YjQ4ZDk5MGZkYzM2MmYyNTk2OGMiLCJ1c2VyTmFtZSI6ImVtYW51ZWwgQWJyZXUiLCJkb2N1bWVudCI6IjI3NTcxNzczIiwicm9sIjoidXNlciIsInBvc2l0aW9uIjoiYW5hbGlzdGEiLCJkZXBhcnRtZW50IjoidGVjbm9sZ2lhIiwiaWF0IjoxNjU4NDU0MzMwLCJleHAiOjE2NTg1NDA3MzB9.UcCtX4ZvglrAkYOM9DchW6vGTArqYab_ZYKPOL2t4vM

###
 POST http://localhost:3200/api/ticket/save-ticket
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ4YjQ4ZDk5MGZkYzM2MmYyNTk2OGMiLCJ1c2VyTmFtZSI6ImVtYW51ZWwgQWJyZXUiLCJkb2N1bWVudCI6IjI3NTcxNzczIiwicm9sIjoidXNlciIsInBvc2l0aW9uIjoiYW5hbGlzdGEiLCJkZXBhcnRtZW50IjoidGVjbm9sZ2lhIiwiaWF0IjoxNjU4NDU0MzMwLCJleHAiOjE2NTg1NDA3MzB9.UcCtX4ZvglrAkYOM9DchW6vGTArqYab_ZYKPOL2t4vM

{
    "userName": "Admin",
    "password": "   Emanuel15"
}
